apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}:{{ .Release.Name }}
rules:
  - verbs:
      - watch
      - list
      - patch
    apiGroups:
      - apps
    resources:
      {{- if .Values.restarter.deployment }}
      - deployments
      {{- end }}
      {{- if .Values.restarter.statefulset }}
      - statefulsets
      {{- end }}
      {{- if .Values.restarter.daemonset }}
      - daemonsets
      {{- end }}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}:{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}:{{ .Release.Name }}